// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.731
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import icons "github.com/AslanSN/CurriculumVitae/components/iconComponents"

func ContactModal() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<input class=\"modal-state\" id=\"modal-contact\" type=\"checkbox\"><div class=\"modal\"><div id=\"alert-container\" class=\"absolute z-40\"></div><label class=\"modal-overlay\" for=\"modal-contact\"></label><div class=\"modal-content flex flex-col gap-5\"><label for=\"modal-contact\" class=\"btn btn-sm btn-circle btn-ghost absolute right-2 top-2\">✕</label><h2 class=\"text-xl\">CONTACT ME</h2><ul><li class=\"flex items-center justify-between\"><b class=\"px-1\">Mobile:</b> <span class=\"px-1\" id=\"mobile\">+34 664 33 06 10</span> <button id=\"mobile-btn\" aria-label=\"Copy Icon Button\" class=\"btn btn-circle btn-sm btn-ghost p-2\" onclick=\"copyText(&#39;mobile&#39;)\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = icons.CopyIcon().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</button></li><li class=\"flex items-center justify-between\"><b class=\"px-1\">Email:</b> <span class=\"px-1\" id=\"mail\">aslan.staub@pm.me</span> <button id=\"mail-btn\" aria-label=\"Copy Icon Button\" class=\"btn btn-circle btn-sm btn-ghost p-2\" onclick=\"copyText(&#39;mail&#39;)\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = icons.CopyIcon().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</button></li></ul><div class=\"flex justify-around gap-3\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = ContactModalFooter().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</div></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}
