// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.707
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

// import (
// 	linkItem "github.com/AslanSN/CV/components/linkItem"
// 	iconLabel "github.com/AslanSN/CV/components/iconLabel"
// 	"github.com/AslanSN/CV/helpers"
// 	"github.com/AslanSN/CV/db/constants"
// 	"errors"
// )

// /**
// * ! Ensayo: recibir los datos desde el back con GO
//  */
// func fetchSocialMediaData() ([]constants.SocialMediaData, error) {
// 	dataFetched, err := helpers.FetchData("info")
// 	socialMediaList, okType := dataFetched.([]constants.SocialMediaData)
// 	if err != nil {
// 		// println("This is an error", err)
// 		return nil, err
// 	}
// 	if !okType {
// 		return nil, errors.New("Type is not expected")
// 	}

// 	return socialMediaList, nil
// }

// // func fetchSocialMediaData() ([]constants.SocialMediaData, error) {
// // 	url := "http://localhost:2340/api/info"
// // 	resp, err := http.Get(url)
// // 	fmt.Printf("Respuesta: %v, Error: %v\n", resp, err)
// // 	if err != nil {
// // 		// println("This is an error", err)
// // 		return nil, err
// // 	}
// // 	// !! IMPORTANTE: Buena práctica para dejar los sockets cerrados y evitar leaks !!
// // 	defer resp.Body.Close()

// // 	body, err := io.ReadAll(resp.Body)
// // 	if err != nil {
// // 		return nil, err
// // 	}

// // 	var data []constants.SocialMediaData
// // 	err = json.Unmarshal(body, &data)
// // 	if err != nil {
// // 		return nil, err
// // 	}

// // 	return data, nil
// // }

// // var socialMediaList, err = fetchSocialMediaData()
func HeroFooterApi() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}

// 	<footer>
// 		<ul
// 			id="social-media-list"
// 			class="flex flex-row items-baseline"
// 		>
// 			if err != nil {
// 				<li class="text-lg">Ups, social media is getting hard to get...</li>
// 			} else {
// 				for _, socialMedia := range constants.SocialMediaList {
// 					<li key={ socialMedia.IconLabelParams.Id }>
// 						@linkItem.LinkItem(socialMedia.SocialMediaLink) {
// 							@iconLabel.IconLabel(socialMedia.IconLabelParams)
// 						}
// 					</li>
// 				}
// 			}
// 		</ul>
// 	</footer>
// }
